import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "@interchain-ui/react/styles";
import Wrapper from "@/components/wrapper";
import Navbar from "@/components/navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const colors = {
    sun: "#F8B994",
    pink: "#FF97D6",
    dark: "#201E1D",
  };
  return (
    <html lang="en">
      <body
        style={{ backgroundColor: colors.dark }}
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen p-8`}
      >
        <Wrapper>
          <div
            style={{ backgroundColor: colors.sun, color: colors.dark }}
            className="max-w-4xl mx-auto mb-6 py-2 px-4 rounded-lg text-center font-medium"
          >
            🔬 MANTRA Chain Testnet (Dukong) Testing Environment
          </div>
          <Navbar />
          {children}{" "}
        </Wrapper>
      </body>
    </html>
  );
}
